name: miachat_app
description: A simple app to send requests to DeepSeek.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.6
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.4
  path_provider: ^2.0.11
  # Aggiunte
  rxdart: ^0.27.7
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png