name: miachat_app
description: A simple app to send requests to DeepSeek.

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.1
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  android:
    default_icon: assets/images/ic_notification.png